import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import scipy.optimize as opt
import time
import datetime
import os
import sys
import pickle
from typing import List, Dict, Tuple, Callable, Optional

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

from SDHawkes_2d_config import alpha, beta, MAXIMUM_STATE_CUTOFF, output_dir
from SDHawkes_2d_sim import create_H


"""
Computing the contractivity condition for state-dependent Hawkes processes example, using the same state-dependence as in the FLLN example in SDHawkes_2d_sim.py.

Plotting/animation code (and only that code) generated by AI (Claude Sonnet 4.5).

NOTE: The LP solver architecture is modular. To use a custom solver:
1. Create an LP parameter constructor function with signature: (H_matrices_list, rho) -> dict
2. Create an LP solver function with signature: (lp_params_dict) -> result_dict
3. Pass both functions to Rho_W_LineSearch and solve_LP_given_rho
See scipy_LP_params_constructor and scipy_LP_solver for reference implementations.
"""

RHO_MAX = np.nextafter(np.float64(1.0), np.float64(0.0))

#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## Configuration Parameters (modify these for your experiment)

# Output directory
OUTPUT_DIR = output_dir

# Rho search parameters
RHO_MIN = np.nextafter(np.float64(0.0), np.float64(1.0))  # first float > 0, used only in bisection search
RHO_MAX = np.nextafter(np.float64(1.0), np.float64(0.0))  # last float < 1, used only in bisection search
RHO_0 = RHO_MAX # Initial guess for line search; only used in line search
RHO_STEP = 0.001 # step size for line search algorithm
RHO_TOL = RHO_STEP # tolerance for bisection search (set equal to step size for fair comparison)

# LP solver parameters
VERBOSE = False

# Animation parameters
TARGET_DURATION = 5.0  # seconds (total duration of animation)
MAX_FRAMES_FOR_GIF = 100  # limit frames for smooth GIF playback


#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## LP Solver Parameter Constructors

def scipy_LP_params_constructor(H_matrices_list: List[np.ndarray], rho: float) -> Dict:
    """
    Construct LP problem parameters for scipy.optimize.linprog.
    
    Formulates the contractivity condition as a linear program:
        find w such that w·H(y) ≤ ρ·w (elementwise) for all y with constraint: w ≥ 1 elementwise
    
    Parameters:
    -----------
    H_matrices_list : list of np.ndarray
        List of H(y) matrices for each feasible state y
    rho : float
        Contractivity parameter ∈ (0,1)
        
    Returns:
    --------
    dict
        Dictionary with keys compatible with scipy.optimize.linprog:
        - 'c': objective function coefficients
        - 'A_ub': inequality constraint matrix
        - 'b_ub': inequality constraint bounds
        - 'A_eq': equality constraint matrix (or None)
        - 'b_eq': equality constraint bounds (or None)
        - 'bounds': variable bounds
        - 'method': solver method
        - 'options': solver options
    """
    # Enforce nonempty state space
    if len(H_matrices_list) == 0:
        raise ValueError("H_matrices_list cannot be empty")
    
    dim = H_matrices_list[0].shape[0]
    
    # Objective: we only care about feasibility, so use zero objective
    c = np.zeros(dim)
    
    # Inequality constraints: w @ (H(y)[:, i] - rho * e_i) <= 0 for all y, all i
    A_ub_list = []
    for H_y in H_matrices_list:
        for i in range(dim):
            # (w @ H(y))[i] <= rho * w[i]
            # sum_j w[j] * H(y)[j, i] <= rho * w[i]
            # sum_j w[j] * H(y)[j, i] - rho * w[i] <= 0
            # w @ (H(y)[:, i] - rho * e_i) <= 0
            e_i = np.zeros(dim)
            e_i[i] = 1
            row = H_y[:, i] - rho * e_i
            A_ub_list.append(row)
    
    A_ub = np.array(A_ub_list)
    b_ub = np.zeros(len(A_ub_list))
    
    # Constraint: w ≥ 1 elementwise (no normalization)
    A_eq = None
    b_eq = None
    bounds = [(1.0, None) for _ in range(dim)]
    
    return {
        'c': c,
        'A_ub': A_ub,
        'b_ub': b_ub,
        'A_eq': A_eq,
        'b_eq': b_eq,
        'bounds': bounds,
        'method': 'highs',
        'options': {'disp': False}
    }


def scipy_LP_solver(lp_params: Dict) -> Dict:
    """
    Solve LP using scipy.optimize.linprog.
    
    Parameters:
    -----------
    lp_params : dict
        Dictionary containing LP problem parameters from scipy_LP_params_constructor
        
    Returns:
    --------
    dict with keys:
        'feasible': bool
        'w': np.ndarray or None (optimal w if feasible)
        'status': str (solver status)
        'solve_time': float (seconds)
    """
    start_time = time.time()
    result = opt.linprog(
        lp_params['c'],
        A_ub=lp_params['A_ub'],
        b_ub=lp_params['b_ub'],
        A_eq=lp_params['A_eq'],
        b_eq=lp_params['b_eq'],
        bounds=lp_params['bounds'],
        method=lp_params['method'],
        options=lp_params['options']
    )
    solve_time = time.time() - start_time
    
    # Package results
    if result.success:
        return {
            'feasible': True,
            'w': result.x,
            'status': result.message,
            'solve_time': solve_time
        }
    else:
        return {
            'feasible': False,
            'w': None,
            'status': result.message,
            'solve_time': solve_time
        }


def solve_LP_given_rho(H_matrices_list: List[np.ndarray], rho: float, lp_solver: Callable, lp_params_constructor: Callable) -> Dict:
    """
    Solve LP feasibility problem for contractivity condition using provided solver and parameter constructor.
    
    Finds weight vector w such that w·H(y) ≤ ρ·w (elementwise) for all feasible states y. Uses the constraint: w ≥ 1 elementwise.
    
    Parameters:
    -----------
    H_matrices_list : list of np.ndarray
        List of H(y) matrices (L¹ norms of excitation kernels) for each feasible state y
    rho : float
        Contractivity parameter ∈ (0,1). Larger rho = easier to satisfy (looser condition)
    lp_solver : callable
        LP solver function that takes lp_params dict and returns result dict
    lp_params_constructor : callable
        Function that constructs LP parameters from (H_matrices_list, rho)
            
    Returns:
    --------
    dict
        Result dictionary from the solver with keys:
        - 'feasible': bool indicating if LP is feasible
        - 'w': np.ndarray or None (optimal w if feasible)
        - 'status': str (solver status message)
        - 'solve_time': float (seconds)
    """
    # Handle empty state space
    if len(H_matrices_list) == 0:
        return {'feasible': False, 'w': None, 'status': 'empty_state_space', 'solve_time': 0.0}
    
    # Construct LP parameters
    lp_params = lp_params_constructor(H_matrices_list, rho)
    
    # Solve LP
    return lp_solver(lp_params)

#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## Iterative Algorithms

def Rho_W_BisectionSearch(H_matrices_list: List[np.ndarray], rho_min: float = RHO_MIN, rho_max: float = RHO_MAX, tol: float = RHO_TOL, lp_solver: Callable = scipy_LP_solver, 
                                lp_params_constructor: Callable = scipy_LP_params_constructor, verbose: bool = True) -> Optional[Tuple[float, np.ndarray, int]]:
    """
    Find the minimum ρ satisfying contractivity condition using bisection search.
    
    Uses binary search to efficiently find the smallest rho value for which the LP is feasible. This is more efficient than line search when you only need the minimum rho, but doesn't provide the full trajectory of (rho, w) pairs needed for visualization.
    
    Since larger rho makes the LP easier to satisfy, we expect:
    - LP is feasible for rho close to 1
    - LP is infeasible for rho close to 0
    - There exists a critical rho* where the transition occurs
    
    Uses the constraint: w ≥ 1 elementwise (no normalization).
    
    Parameters:
    -----------
    H_matrices_list : list of np.ndarray
        List of H(y) matrices for each feasible state y
    rho_min : float, optional
        Lower bound for bisection search (default: RHO_MIN)
    rho_max : float, optional
        Upper bound for bisection search (default: RHO_MAX)
    tol : float, optional
        Tolerance for bisection convergence (default: RHO_TOL)
    lp_solver : callable, optional
        LP solver function (default: scipy_LP_solver)
    lp_params_constructor : callable, optional
        LP parameter constructor function (default: scipy_LP_params_constructor)
    verbose : bool, optional
        If True, print progress information (default: True)
        
    Returns:
    --------
    tuple of (rho_critical, w_critical, num_iterations) or None
        - rho_critical : float
            Minimum rho value for which LP is feasible (within tolerance)
        - w_critical : np.ndarray
            Weight vector w corresponding to rho_critical
        - num_iterations : int
            Number of bisection iterations performed
        Returns None if LP is infeasible even at rho_max
    """
    rho_plus = rho_max
    rho_minus = rho_min
    num_iterations = 0
    
    if verbose:
        print(f"Starting bisection search for minimum rho")
        print(f"Search interval: [{rho_min:.10f}, {rho_max:.10f}]")
        print(f"Tolerance: {tol}")
        print(f"Using solver: {lp_solver.__name__}")
        print("-" * 60)

    # Check upper bound
    U = solve_LP_given_rho(H_matrices_list, rho_plus, lp_solver, lp_params_constructor)
    num_iterations += 1
    if not U['feasible']:
        if verbose:
            print(f"LP infeasible even at rho_max = {rho_max:.10f}")
            print("No contractivity condition can be satisfied.")
        return None
    
    # Check lower bound
    L = solve_LP_given_rho(H_matrices_list, rho_minus, lp_solver, lp_params_constructor)
    num_iterations += 1
    if L['feasible']:
        if verbose:
            print(f"LP feasible at rho_min = {rho_minus:.10f}")
            print(f"Minimum rho found: {rho_minus:.10f}")
            print(f"w = {L['w']}")
        return rho_minus, L['w'], num_iterations

    # Bisection search
    while (rho_plus - rho_minus) > tol:
        rho_mid = (rho_plus + rho_minus) / 2
        M = solve_LP_given_rho(H_matrices_list, rho_mid, lp_solver, lp_params_constructor)
        num_iterations += 1
        
        if M['feasible']:
            rho_plus = rho_mid
            w_best = M['w']
            if verbose and num_iterations % 5 == 0:
                print(f"Iteration {num_iterations}: rho = {rho_mid:.10f} - FEASIBLE")
        else:
            rho_minus = rho_mid
            if verbose and num_iterations % 5 == 0:
                print(f"Iteration {num_iterations}: rho = {rho_mid:.10f} - INFEASIBLE")
    
    if verbose:
        print("-" * 60)
        print(f"Bisection converged after {num_iterations} iterations")
        print(f"Minimum rho found: {rho_plus:.10f}")
        print(f"Final interval width: {rho_plus - rho_minus:.2e}")
        print(f"w = {w_best}")

    return rho_plus, w_best, num_iterations


# For plotting purposes, we also code a line-search method; being able to control the step-size results in ``continuous" pictures of the evolution of w as rho gets contracted
def Rho_W_LineSearch(H_matrices_list: List[np.ndarray], rho_0: float = RHO_0, rho_step: float = 0.001, rho_min: float = 0.0, lp_solver: Callable = scipy_LP_solver, 
                                lp_params_constructor: Callable = scipy_LP_params_constructor, verbose: bool = True) -> Tuple[List[float], List[np.ndarray]]:
    """
    Iteratively find (ρ, w) pairs satisfying contractivity condition by decreasing ρ.
    
    Starting from rho_0 (close to 1), decreases rho by rho_step until either:
    1. LP becomes infeasible (no valid w exists), or
    2. rho reaches rho_min
    
    Since larger rho makes the LP easier to satisfy, we expect feasibility for large rho
    and infeasibility for small rho. This function finds the transition region.
    
    Uses the constraint: w ≥ 1 elementwise (no normalization).
    
    Parameters:
    -----------
    H_matrices_list : list of np.ndarray
        List of H(y) matrices for each feasible state y
    rho_0 : float, optional
        Initial (largest) rho value to test (default: 0.999999)
    rho_step : float, optional
        Amount to decrease rho each iteration (default: 0.001)
    rho_min : float, optional
        Minimum rho value to test; stop if rho < rho_min (default: 0.0)
    lp_solver : callable, optional
        LP solver function (default: scipy_LP_solver)
    lp_params_constructor : callable, optional
        LP parameter constructor function (default: scipy_LP_params_constructor)
    verbose : bool, optional
        If True, print progress information (default: True)
        
    Returns:
    --------
    tuple of (rho_list, w_list)
        - rho_list : list of float
            All rho values for which LP was feasible
        - w_list : list of np.ndarray
            Corresponding weight vectors w for each feasible rho
    """

    rho_list = []
    w_list = []
    
    # Validate input parameters
    if rho_min < 0:
        raise ValueError("rho_min must be non-negative")
    if rho_0 >= 1.0:
        raise ValueError(f"rho_0 must be strictly less than 1 (got rho_0 = {rho_0}). "
                        "The contractivity parameter rho must satisfy 0 <= rho < 1.")
    if rho_step <= 0:
        raise ValueError(f"rho_step must be positive (got rho_step = {rho_step})")
    
    # Initialize rho at starting value
    rho = rho_0
    
    if verbose:
        print(f"Finding contractivity pairs starting from rho = {rho_0}")
        print(f"Decreasing by {rho_step} until infeasible or rho < {rho_min}")
        print(f"Using solver: {lp_solver.__name__}")
        print("-" * 60)

    # Iterate: decrease rho until infeasible or below minimum
    iteration = 0
    while rho >= rho_min:
        iteration += 1
        
        # Solve LP for current rho
        result = solve_LP_given_rho(H_matrices_list, rho, lp_solver, lp_params_constructor)
        
        if result['feasible']:
            # Store feasible (rho, w) pair
            rho_list.append(rho)
            w_list.append(result['w'])
            
            if verbose and iteration % 10 == 0:
                print(f"Iteration {iteration}: rho = {rho:.6f} - FEASIBLE (w = {result['w']})")
        else:
            # LP became infeasible - stop iteration
            if verbose:
                print(f"Iteration {iteration}: rho = {rho:.6f} - INFEASIBLE")
                print(f"Stopping: LP is infeasible for rho = {rho:.6f}")
            break
        
        # Decrease rho for next iteration
        rho -= rho_step
    
    if verbose:
        if rho < rho_min:
            print(f"Stopping: reached minimum rho = {rho_min}")
        print("-" * 60)
        print(f"Found {len(rho_list)} feasible (rho, w) pairs")
        if len(rho_list) > 0:
            print(f"Rho range: [{min(rho_list):.6f}, {max(rho_list):.6f}]")
    
    return rho_list, w_list

#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## Helper Functions

def write_contractivity_parameters(subfolder_path: str, rho_0: float, rho_step: float, rho_min: float, rho_final: float, 
                                   num_pairs: int, solver_name: str, timestamp: str, bisection_result: Optional[Dict] = None) -> str:
    """
    Write contractivity condition experiment parameters to a text file.
    
    Parameters:
    -----------
    subfolder_path : str
        Path to the subfolder where the parameter file should be saved
    rho_0 : float
        Initial rho value
    rho_step : float
        Step size for decreasing rho
    rho_min : float
        Minimum rho value (stopping condition)
    rho_final : float
        Final rho value achieved (where LP became infeasible)
    num_pairs : int
        Number of feasible (rho, w) pairs found
    solver_name : str
        Name of LP solver used
    timestamp : str
        Timestamp string for the experiment run
    bisection_result : dict, optional
        Results from bisection search with keys 'rho', 'w', 'iterations'
        
    Returns:
    --------
    str
        Path to the created parameter file
    """
    # Import global parameters from SDHawkes_2d_config
    from SDHawkes_2d_config import alpha, beta, delta, dim, MAXIMUM_STATE_CUTOFF
    
    param_file = os.path.join(subfolder_path, "contractivity_parameters.txt")
    
    with open(param_file, 'w') as f:
        f.write("=" * 70 + "\n")
        f.write("CONTRACTIVITY CONDITION EXPERIMENT PARAMETERS\n")
        f.write("=" * 70 + "\n\n")
        
        f.write("EXPERIMENT METADATA\n")
        f.write("-" * 70 + "\n")
        f.write(f"Timestamp: {timestamp}\n")
        f.write(f"Subfolder: {os.path.basename(subfolder_path)}\n\n")
        
        f.write("CONTRACTIVITY SEARCH PARAMETERS\n")
        f.write("-" * 70 + "\n")
        f.write(f"Initial rho (rho_0): {rho_0}\n")
        f.write(f"Rho step size: {rho_step}\n")
        f.write(f"Minimum rho (rho_min): {rho_min}\n")
        f.write(f"Final rho achieved: {rho_final}\n")
        f.write(f"Number of feasible (rho, w) pairs found: {num_pairs}\n\n")
        
        f.write("LP SOLVER PARAMETERS\n")
        f.write("-" * 70 + "\n")
        f.write(f"Solver: {solver_name}\n")
        f.write(f"Constraint: w >= 1 elementwise (no normalization)\n\n")
        
        f.write("HAWKES PROCESS PARAMETERS\n")
        f.write("-" * 70 + "\n")
        f.write(f"Dimension: {dim}\n\n")
        
        f.write(f"Alpha (excitation matrix):\n")
        for row in alpha:
            f.write(f"  {row}\n")
        f.write("\n")
        
        f.write(f"Beta (decay matrix):\n")
        for row in beta:
            f.write(f"  {row}\n")
        f.write("\n")
        
        f.write(f"Delta (state-dependency parameter): {delta}\n\n")
        
        f.write("STATE SPACE\n")
        f.write("-" * 70 + "\n")
        f.write(f"Maximum State Cutoff: {MAXIMUM_STATE_CUTOFF}\n")
        f.write(f"State transformation matrix M: [[1, -1]]\n")
        f.write(f"Number of states: {2 * MAXIMUM_STATE_CUTOFF + 1}\n")
        f.write(f"State range: [{-MAXIMUM_STATE_CUTOFF}, {MAXIMUM_STATE_CUTOFF}]\n\n")
        
        # Add bisection search results if provided
        if bisection_result is not None:
            f.write("BISECTION SEARCH RESULTS\n")
            f.write("-" * 70 + "\n")
            f.write(f"Minimum rho (bisection): {bisection_result['rho']:.10f}\n")
            f.write(f"Number of iterations: {bisection_result['iterations']}\n")
            f.write(f"Weight vector w:\n")
            for i, w_i in enumerate(bisection_result['w']):
                f.write(f"  w[{i}] = {w_i:.6f}\n")
            f.write("\n")
            
            # Compare with line search if available
            if rho_final is not None:
                f.write("COMPARISON: BISECTION vs LINE SEARCH\n")
                f.write("-" * 70 + "\n")
                f.write(f"Bisection minimum rho: {bisection_result['rho']:.10f}\n")
                f.write(f"Line search minimum rho: {rho_final:.10f}\n")
                f.write(f"Difference: {abs(bisection_result['rho'] - rho_final):.2e}\n")
                f.write(f"Bisection iterations: {bisection_result['iterations']}\n")
                f.write(f"Line search evaluations: {num_pairs}\n")
                f.write("\n")
        
        f.write("=" * 70 + "\n")
    
    return param_file


#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## Plotting

def plot_evolution_static(rho_list: List[float], w_list: List[np.ndarray], output_path: str, title: str = "Contractivity Vector Evolution") -> None:
    """
    Create static plot showing evolution of weight vectors w as rho changes.
    
    Visualizes w vectors as arrows from origin, colored by their corresponding rho value.
    Color gradient: blue (large ρ, easier condition) → red (small ρ, harder condition).
    
    This function is designed to be general and work for any dimension d, though it's
    most interpretable for d=2 (2D arrows).
    
    Parameters:
    -----------
    rho_list : list of float
        List of rho values (contractivity parameters)
    w_list : list of np.ndarray
        List of corresponding weight vectors w
    output_path : str
        Path to save the plot (e.g., 'w_evolution.png')
    title : str, optional
        Plot title (default: "Contractivity Weight Vector Evolution")
        
    Returns:
    --------
    None
        Saves plot to output_path
        
    Notes:
    ------
    - For d=2: Creates 2D arrow plot
    - For d>2: Creates parallel coordinates plot or component-wise visualization
    - Requires matplotlib
    """
    import datetime
    
    if len(rho_list) == 0:
        print("Warning: No data to plot (empty rho_list)")
        return
    
    rho_array = np.array(rho_list)
    w_array = np.array(w_list)  # Shape: (num_points, dim)
    dim = w_array.shape[1]
    
    # Create figure
    fig, ax = plt.subplots(figsize=(10, 8))
    
    if dim == 2:
        # 2D case: arrow plot
        # Normalize rho values to [0, 1] for colormap
        rho_normalized = (rho_array - rho_array.min()) / (rho_array.max() - rho_array.min() + 1e-10)
        
        # Use colormap: blue (high rho) to red (low rho)
        cmap = plt.cm.coolwarm_r  # reversed coolwarm: blue=high, red=low
        colors = cmap(rho_normalized)
        
        # Determine axis limits to make plot square
        # Find the maximum value across both w_1 and w_2 components
        w_max = max(np.max(w_array[:, 0]), np.max(w_array[:, 1]))
        axis_limit = w_max * 1.1  # Add 10% padding
        
        # Plot arrows
        for i, (w, color) in enumerate(zip(w_array, colors)):
            ax.arrow(0, 0, w[0], w[1], 
                    head_width=0.02, head_length=0.02, 
                    fc=color, ec=color, alpha=0.7, 
                    length_includes_head=True, linewidth=1.5)
        
        # Add colorbar (ensure vmax < 1 since rho must be strictly less than 1)
        # Set vmax to the smaller of: actual max or 0.99 (to ensure colorbar never shows >= 1)
        rho_max_display = min(rho_array.max(), 0.99)
        # Ensure vmin is also reasonable and less than vmax
        rho_min_display = min(rho_array.min(), rho_max_display - 0.01)
        sm = plt.cm.ScalarMappable(cmap=cmap, 
                                   norm=plt.Normalize(vmin=rho_min_display, vmax=rho_max_display))
        sm.set_array([])
        cbar = plt.colorbar(sm, ax=ax)
        cbar.set_label('ρ (contractivity parameter)', fontsize=12)
        # Format colorbar ticks to show they're all < 1
        cbar.ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:.3f}'))
        
        # Labels and formatting
        ax.set_xlabel('$w_1$', fontsize=14)
        ax.set_ylabel('$w_2$', fontsize=14)
        ax.set_title(title, fontsize=16)
        ax.grid(True, alpha=0.3)
        ax.axhline(y=0, color='k', linewidth=0.5)
        ax.axvline(x=0, color='k', linewidth=0.5)
        
        # Set equal axis limits to make plot square
        ax.set_xlim(-0.05 * axis_limit, axis_limit)
        ax.set_ylim(-0.05 * axis_limit, axis_limit)
        ax.set_aspect('equal', adjustable='box')
        
        # Add text annotations for first and last (rho, w) pairs at top of plot
        first_rho, first_w = rho_array[0], w_array[0]
        last_rho, last_w = rho_array[-1], w_array[-1]
        text_y_pos = axis_limit * 0.95  # Position near top of plot
        ax.text(0.02, text_y_pos, 
                f'First: ρ={first_rho:.6f}, w=[{first_w[0]:.3f}, {first_w[1]:.3f}]',
                fontsize=10, verticalalignment='top', 
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
        ax.text(0.02, text_y_pos - axis_limit * 0.08,
                f'Last: ρ={last_rho:.6f}, w=[{last_w[0]:.3f}, {last_w[1]:.3f}]',
                fontsize=10, verticalalignment='top',
                bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.5))
        
    else:
        # Higher dimensional case: parallel coordinates plot
        for i, (rho, w) in enumerate(zip(rho_array, w_array)):
            # Normalize rho for color
            rho_norm = (rho - rho_array.min()) / (rho_array.max() - rho_array.min() + 1e-10)
            color = plt.cm.coolwarm_r(rho_norm)
            
            # Plot line connecting w components
            ax.plot(range(dim), w, '-o', color=color, alpha=0.6, linewidth=1.5)
        
        # Add colorbar (ensure vmax < 1 since rho must be strictly less than 1)
        # Set vmax to the smaller of: actual max or 0.99 (to ensure colorbar never shows >= 1)
        rho_max_display = min(rho_array.max(), 0.99)
        # Ensure vmin is also reasonable and less than vmax
        rho_min_display = min(rho_array.min(), rho_max_display - 0.01)
        sm = plt.cm.ScalarMappable(cmap=plt.cm.coolwarm_r, 
                                   norm=plt.Normalize(vmin=rho_min_display, vmax=rho_max_display))
        sm.set_array([])
        cbar = plt.colorbar(sm, ax=ax)
        cbar.set_label('ρ (contractivity parameter)', fontsize=12)
        # Format colorbar ticks to show they're all < 1
        cbar.ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:.3f}'))
        
        # Labels
        ax.set_xlabel('Component index', fontsize=14)
        ax.set_ylabel('$w_i$', fontsize=14)
        ax.set_title(title, fontsize=16)
        ax.set_xticks(range(dim))
        ax.set_xticklabels([f'$w_{i+1}$' for i in range(dim)])
        ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Static plot saved to: {output_path}")
    plt.close()


def plot_evolution_animated(rho_list: List[float], w_list: List[np.ndarray], output_path: str, title: str = "Contractivity Vector Evolution", 
                           interval: int = 200) -> None:
    """
    Create animated GIF showing how weight vector w evolves as rho decreases.
    
    Shows a "movie" of w changing over time (parameterized by rho) without an explicit
    rho axis. For d=2, animates an arrow; for d>2, animates a bar chart.
    
    Parameters:
    -----------
    rho_list : list of float
        List of rho values (contractivity parameters), should be in decreasing order
    w_list : list of np.ndarray
        List of corresponding weight vectors w
    output_path : str
        Path to save animation (must end in .gif)
    title : str, optional
        Base title for animation (default: "Contractivity Weight Vector Evolution")
    interval : int, optional
        Delay between frames in milliseconds (default: 200)
        
    Returns:
    --------
    None
        Saves animation to output_path
        
    Notes:
    ------
    - Uses pillow writer for GIF output
    - Animation shows rho value in title for each frame
    """
    if len(rho_list) == 0:
        print("Warning: No data to animate (empty rho_list)")
        return
    
    rho_array = np.array(rho_list)
    w_array = np.array(w_list)
    dim = w_array.shape[1]
    
    # Ensure output path ends with .gif
    if not output_path.endswith('.gif'):
        output_path += '.gif'
    
    writer = 'pillow'
    
    # Create figure
    fig, ax = plt.subplots(figsize=(10, 8))
    
    if dim == 2:
        # 2D case: animate arrow
        # Set axis limits based on data range
        w_max = np.max(np.abs(w_array)) * 1.2
        ax.set_xlim(-0.1, w_max)
        ax.set_ylim(-0.1, w_max)
        ax.set_xlabel('$w_1$', fontsize=14)
        ax.set_ylabel('$w_2$', fontsize=14)
        ax.grid(True, alpha=0.3)
        ax.set_aspect('equal', adjustable='box')
        
        # Initialize arrow
        arrow = ax.arrow(0, 0, w_array[0, 0], w_array[0, 1],
                        head_width=0.05*w_max, head_length=0.05*w_max,
                        fc='blue', ec='blue', linewidth=2,
                        length_includes_head=True)
        title_text = ax.set_title(f"{title}\nρ = {rho_array[0]:.6f}", fontsize=16)
        
        def update_arrow(frame):
            """Update function for animation"""
            ax.clear()
            ax.set_xlim(-0.1, w_max)
            ax.set_ylim(-0.1, w_max)
            ax.set_xlabel('$w_1$', fontsize=14)
            ax.set_ylabel('$w_2$', fontsize=14)
            ax.grid(True, alpha=0.3)
            ax.set_aspect('equal', adjustable='box')
            
            w = w_array[frame]
            ax.arrow(0, 0, w[0], w[1],
                    head_width=0.05*w_max, head_length=0.05*w_max,
                    fc='blue', ec='blue', linewidth=2,
                    length_includes_head=True)
            ax.set_title(f"{title}\nρ = {rho_array[frame]:.6f}", fontsize=16)
            return ax,
        
        anim = animation.FuncAnimation(fig, update_arrow, frames=len(rho_list),
                                      interval=interval, blit=False, repeat=True)
    
    else:
        # Higher dimensional case: animate bar chart
        # Set axis limits
        w_max = np.max(w_array) * 1.1
        w_min = min(0, np.min(w_array) * 1.1)
        
        ax.set_ylim(w_min, w_max)
        ax.set_xlabel('Component index', fontsize=14)
        ax.set_ylabel('$w_i$', fontsize=14)
        ax.set_xticks(range(dim))
        ax.set_xticklabels([f'$w_{i+1}$' for i in range(dim)])
        ax.grid(True, alpha=0.3, axis='y')
        
        # Initialize bars
        bars = ax.bar(range(dim), w_array[0], color='blue', alpha=0.7)
        title_text = ax.set_title(f"{title}\nρ = {rho_array[0]:.6f}", fontsize=16)
        
        def update_bars(frame):
            """Update function for animation"""
            w = w_array[frame]
            for bar, height in zip(bars, w):
                bar.set_height(height)
            title_text.set_text(f"{title}\nρ = {rho_array[frame]:.6f}")
            return bars + [title_text]
        
        anim = animation.FuncAnimation(fig, update_bars, frames=len(rho_list),
                                      interval=interval, blit=True, repeat=True)
    
    # Save animation
    print(f"Saving animation to: {output_path}")
    anim.save(output_path, writer=writer)
    print(f"Animation saved successfully")
    plt.close()


#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## Main Script

if __name__ == "__main__":

    # Create H function
    H_func = create_H(alpha, beta)
    
    # Generate possible states given the state cutoff, that the state matrix is [1,-1], and that counting vectors have non-negative integer entries.
    state_array = np.arange(-MAXIMUM_STATE_CUTOFF, MAXIMUM_STATE_CUTOFF + 1)
    
    # Compute H matrices for all states - simple list comprehension is efficient
    H_matrices_list = [H_func(y) for y in state_array]
    
    # Validate rho_0 is strictly less than 1
    if RHO_0 >= 1.0:
        raise ValueError(f"rho_0 must be strictly less than 1 (got rho_0 = {RHO_0}). "
                        "The contractivity parameter rho must satisfy 0 <= rho < 1.")
    
    # First, run bisection search to find minimum rho efficiently
    print("\n" + "="*70)
    print("BISECTION SEARCH")
    print("="*70)
    bisection_tol = RHO_STEP  # Use same tolerance as line search step size for fair comparison
    bisection_result_tuple = Rho_W_BisectionSearch(H_matrices_list, RHO_MIN, RHO_MAX, bisection_tol,
                                                     scipy_LP_solver, scipy_LP_params_constructor, verbose=True)
    
    if bisection_result_tuple is not None:
        rho_bisection, w_bisection, bisection_iters = bisection_result_tuple
        bisection_result = {
            'rho': rho_bisection,
            'w': w_bisection,
            'iterations': bisection_iters
        }
    else:
        bisection_result = None
        print("\nWARNING: Bisection search failed - no feasible rho found.")
    
    # Then run line search for visualization purposes
    print("\n" + "="*70)
    print("LINE SEARCH (for visualization)")
    print("="*70)
    rho_list, w_list = Rho_W_LineSearch(H_matrices_list, RHO_0, RHO_STEP, RHO_MIN, 
                                                 scipy_LP_solver, scipy_LP_params_constructor, VERBOSE)
    
    # Generate plots and save results only if feasible pairs were found
    if len(rho_list) > 0:
        # Create timestamped subfolder for this experiment
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        rho_step_str = f"{RHO_STEP:.0e}" # Format rho_step in scientific notation (e.g., 0.001 -> 1e-03, 0.1 -> 1e-01)
        solver_name = scipy_LP_solver.__name__
        subfolder_name = f"Contractivity_step_{rho_step_str}_{solver_name}_{timestamp}"
        subfolder_path = os.path.join(OUTPUT_DIR, subfolder_name)
        os.makedirs(subfolder_path, exist_ok=True)
        print(f"\nCreated output folder: {subfolder_path}")
        
        # Determine final rho achieved
        rho_final = min(rho_list)
        
        # Write experiment parameters to file
        param_file = write_contractivity_parameters(
            subfolder_path, RHO_0, RHO_STEP, RHO_MIN, rho_final, 
            len(rho_list), solver_name, timestamp, bisection_result
        )
        print(f"Saved experiment parameters to: {param_file}\n")
        
        # Save (rho, w) pairs to pickle file
        data_dict = {
            'rho_list': rho_list,
            'w_list': w_list,
            'rho_array': np.array(rho_list),
            'w_array': np.array(w_list)
        }
        pkl_file = os.path.join(subfolder_path, "rho_w_pairs.pkl")
        with open(pkl_file, 'wb') as f:
            pickle.dump(data_dict, f)
        print(f"Saved (rho, w) pairs to: {pkl_file}\n")
        
        # Static plot
        static_plot_path = os.path.join(subfolder_path, "w_evolution_static.png")
        plot_evolution_static(rho_list, w_list, static_plot_path, 
                            title="Contractivity Vector Evolution")
        
        # Animated plot (GIF)
        animated_plot_path = os.path.join(subfolder_path, "w_evolution_animated.gif")
        
        # For smooth GIF playback, limit to ~100 frames (browsers struggle with >200 frames)
        # Subsample if we have too many frames
        if len(rho_list) > MAX_FRAMES_FOR_GIF:
            indices = np.linspace(0, len(rho_list) - 1, MAX_FRAMES_FOR_GIF, dtype=int)
            rho_list_anim = [rho_list[i] for i in indices]
            w_list_anim = [w_list[i] for i in indices]
            num_frames = MAX_FRAMES_FOR_GIF
        else:
            rho_list_anim = rho_list
            w_list_anim = w_list
            num_frames = len(rho_list)
        
        # Calculate interval to match target duration
        interval = int((TARGET_DURATION * 1000) / num_frames)  # milliseconds per frame
        
        plot_evolution_animated(rho_list_anim, w_list_anim, animated_plot_path, 
                               title="Contractivity Vector Evolution", 
                               interval=interval)
        
        print(f"\nExperiment complete! All outputs saved to: {subfolder_path}")
    else:
        print("\nWarning: No feasible (rho, w) pairs found. No plots generated.")